{{- if .Values.prometheusConfig.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheusConfig.name }}
  namespace: {{ include "istio-metrics.prometheusNamespace" . }}
  labels:
    {{- include "istio-metrics.labels" . | nindent 4 }}
data:
  {{- if .Values.prometheusConfig.customConfig }}
  # User-provided custom configuration
  {{- toYaml .Values.prometheusConfig.customConfig | nindent 2 }}
  {{- else }}
  # Default Prometheus configuration with recording rules
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - /etc/config/recording_rules.yml
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'k8s-labels-exporter'
        static_configs:
          - targets: ['k8s-labels-exporter:{{ .Values.exporter.port }}']
      
      # Add more scrape configs as needed
      {{- if .Values.prometheusConfig.additionalScrapeConfigs }}
      {{- .Values.prometheusConfig.additionalScrapeConfigs | nindent 6 }}
      {{- end }}
  
  recording_rules.yml: |
    {{- .Files.Get "files/recording_rules.yml" | nindent 4 }}
  {{- end }}
{{- end }}