{{- if .Values.envoy.filters.preserveExternalRequestId.enabled }}
# Override Envoy default behavior: when a client sends X-Request-ID + X-Forwarded-For,
# Envoy drops the incoming request-id. This filter preserves it for end-to-end tracing.
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: request-id-config
  namespace: {{ .Values.namespaces.gateway }}
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          preserve_external_request_id: true
          use_remote_address: false
          skip_xff_append: false
{{- end }}
