{{- if .Values.rbac.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nullplatform-agent.fullname" . }}
  labels:
    {{ include "nullplatform-agent.labels" . | nindent 4 }}
rules:
{{- with .Values.rbac.clusterRole.rules }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{ end }}