apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nullplatform-agent.labels" . | nindent 4 }}
data:
  {{- range $i, $cmd := .Values.initScripts }}
    {{ printf "%02d-script.sh" (add1 $i) }}: |
      {{ $cmd }}
  {{- end }}