{{- if .Values.configuration.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nullplatform-agent.fullname" . }}
  labels:
    {{ include "nullplatform-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.configuration.values }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}