{{- if and .Values.github.apps .Values.github.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.githubAppsSecretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.github.apps }}
  {{- if not .privateKeySsmParameter }}
  {{ .privateKeySecretKey | default (printf "%s.pem" (lower .org)) }}: {{ .privateKey | toString | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
