{{- if .Values.imagePullSecret.create }}
{{- $registry := required "The 'registry' field is required when imagePullSecret.create is true" .Values.imagePullSecret.registry }}
{{- $username := required "The 'username' field is required when imagePullSecret.create is true" .Values.imagePullSecret.username }}
{{- $password := required "The 'password' field is required when imagePullSecret.create is true" .Values.imagePullSecret.password }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"auth\": \"%s\"}}}" $registry $username $password $auth | b64enc }}
{{- end }}
