{{- if .Values.configuration.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configuration.secretName }}-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.configuration.values }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
