apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: "{{ .Values.namespacecontroller.name }}"
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.{{ .Values.hostedZoneName }}"
  dnsNames:
  - "{{ .Values.hostedZoneName }}"
  - "*.{{ .Values.hostedZoneName }}"
  {{- if .Values.nullPlatform.accountSlug }}
  - "*.{{ .Values.nullPlatform.accountSlug }}.{{ .Values.hostedZoneName }}"
  {{- end }}
