apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-azure
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it@nullplatform.io
    privateKeySecretRef:
      name: letsencrypt-azure
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: {{ .Values.azure.subscriptionId }}
          resourceGroupName: {{ .Values.azure.resourceGroupName }}
          hostedZoneName: {{ .Values.azure.hostedZoneName }}
          environment: AzurePublicCloud
          managedIdentity:
            clientID: {{ .Values.azure.clientId }}
