{{- if .Values.gcp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-cloud-dns-service-account
  namespace: cert-manager
type: Opaque
data:
  key.json: {{ .Values.gcp.serviceAccountKey | b64enc | quote }}
{{- end }}
