{{- if and .Values.azure.enabled .Values.azure.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: azuredns-config
  namespace: cert-manager
type: Opaque
stringData:
  {{ .Values.azure.secretKey | default "client-secret" }}: {{ .Values.azure.clientSecret | quote }}
{{- end }}