{{- if .Values.logging.datadog.enabled }}
{{ $apiKey := required "The 'logging.datadog.apiKey' field is required when logging.datadog.enabled is true" .Values.logging.datadog.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: nullplatform-tools
type: Opaque
data:
  DATADOG_API_KEY: {{ $apiKey | b64enc | quote }}
{{- end }}
