{{- if .Values.logging.datadog.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: nullplatform-tools
type: Opaque
data:
  DATADOG_API_KEY: {{ .Values.logging.datadog.apiKey | b64enc | quote }}
{{- end }}
