apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-finalizer
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-finalizer
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: blocker
          image: alpine:latest
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          command:
            - /bin/sh
            - -c
            - |
              echo "⛔ DELETION BLOCKED ⛔"
              echo "========================================================"
              echo "Please contact Nullplatform team in order to uninstall the chart: {{ .Release.Name }}"
              echo "========================================================"

              # This job will remain running indefinitely, preventing the pre-delete hook from completing
              # which in turn prevents Helm from deleting the release
              while true; do
                echo "Chart deletion blocked for release: {{ .Release.Name }}. Please contact Nullplatform team."
                sleep 3600
              done
