apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.gateway | default "gateways" }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    name: {{ .Values.namespaces.gateway | default "gateways" }}
