{{- if .Values.imagePullSecrets.enabled }}
{{- $registry := required "The 'registry' field is required when imagePullSecrets is enabled" .Values.imagePullSecrets.registry }}
{{- $username := required "The 'username' field is required when imagePullSecrets is enabled" .Values.imagePullSecrets.username }}
{{- $password := required "The 'password' field is required when imagePullSecrets is enabled" .Values.imagePullSecrets.password }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.namespaces.nullplatformApplications }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"auth\": \"%s\"}}}" $registry $username $password $auth | b64enc }}
{{- end }}
