{{- if and .Values.logging.enabled (eq .Values.logging.mode "istio-metrics") }}
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: gateway-metrics-response-code
  namespace: {{ .Values.logging.istioMetrics.gatewaysNamespace }}
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: REQUEST_COUNT
      tagOverrides:
        response_code:
          value: response.code | "unknown"
        destination_pod_ip:
          value: destination.ip | "unknown"
    - match:
        metric: REQUEST_DURATION
      tagOverrides:
        response_code:
          value: response.code | "unknown"
        destination_pod_ip:
          value: destination.ip | "unknown"
    - match:
        metric: REQUEST_SIZE
      tagOverrides:
        response_code:
          value: response.code | "unknown"
        destination_pod_ip:
          value: destination.ip | "unknown"
    - match:
        metric: RESPONSE_SIZE
      tagOverrides:
        response_code:
          value: response.code | "unknown"
        destination_pod_ip:
          value: destination.ip | "unknown"
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stats-filter-response-code
  namespace: {{ .Values.logging.istioMetrics.gatewaysNamespace }}
spec:
  workloadSelector:
    labels:
      gateway.networking.k8s.io/gateway-name: {{ .Values.gateway.public.name }}
  configPatches:
  # Add response_code to istio metrics
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "istio.stats"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/stats.PluginConfig
          metrics:
          - dimensions:
              response_code: response.code
              destination_pod_ip: upstream.address
{{- if .Values.gateway.internal.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stats-filter-response-code-private
  namespace: {{ .Values.logging.istioMetrics.gatewaysNamespace }}
spec:
  workloadSelector:
    labels:
      gateway.networking.k8s.io/gateway-name: {{ .Values.gateway.internal.name }}
  configPatches:
  # Add response_code to istio metrics
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "istio.stats"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/stats.PluginConfig
          metrics:
          - dimensions:
              response_code: response.code
              destination_pod_ip: upstream.address
{{- end }}
{{- end }}