{{- if .Values.controlPlane.enabled }}
{{ $nullplatformApiKey := required "The 'nullplatform.apiKey' field is required when controlPlane.enabled is true. Checkout our doc on how to create api keys" .Values.nullplatform.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: nullplatform-secret
  namespace: nullplatform-tools
type: Opaque
data:
  NULLPLATFORM_APIKEY: {{ $nullplatformApiKey | b64enc | quote }}
{{- end }}
