{{- if .Values.controlPlane.enabled }}
{{- if and (not .Values.nullplatform.apiKey) (not .Values.nullplatform.secretName) }}
{{- fail "Either 'nullplatform.apiKey' or 'nullplatform.secretName' must be provided when controlPlane.enabled is true. Checkout our doc on how to create api keys" }}
{{- end }}
{{- $nullplatformApiKey := .Values.nullplatform.apiKey }}

{{- if $nullplatformApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: nullplatform-secret
  namespace: {{ .Values.namespaces.nullplatformTools }}
type: Opaque
data:
  NULLPLATFORM_APIKEY: {{ $nullplatformApiKey | b64enc | quote }}
{{- end }}
{{- end }}