{{- if .Values.global.installGatewayV2Crd }}
apiVersion: batch/v1
kind: Job
metadata:
  name: install-gateway-api-crds
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  template:
    spec:
      serviceAccountName: nullplatform-crd-installer-sa
      containers:
      - name: install-crds
        image: docker.io/bitnamilegacy/kubectl:1.31.4
        command:
          - /bin/sh
          - -c
          - |
            kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref={{ .Values.global.gatewayApiCrdRef }}" | kubectl apply --server-side --force-conflicts -f -
      restartPolicy: OnFailure
{{- end }}
