apiVersion: v1
kind: ServiceAccount
metadata:
  name: nullplatform-pod-metadata-reader-sa
  namespace: {{ .Values.namespaces.nullplatformTools }}
  {{- if and .Values.cloudwatch.enabled .Values.cloudwatch.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.cloudwatch.serviceAccount.annotations | nindent 4 }}
  {{- end }}
---
{{- if .Values.global.installGatewayV2Crd }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nullplatform-crd-installer-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
{{- end }}
---
{{- if .Values.logging.ensureLease }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nullplatform-lease-installer-sa
  namespace: {{ .Values.namespaces.nullplatformTools }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
{{- end }}
