apiVersion: v1
kind: Namespace
metadata:
  name: nullplatform-tools
  labels:
    name: nullplatform-tools
---
{{- if not (lookup "v1" "Namespace" "" .Values.namespaces.nullplatform) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.nullplatform }}
  labels:
    name: {{ .Values.namespaces.nullplatform }}
{{- end }}
---
{{- if .Values.istio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
---
{{- if not (lookup "v1" "Namespace" "" .Values.namespaces.gateway) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.gateway }}
  labels:
    name: {{ .Values.namespaces.gateway }}
{{- end }}
{{- end }}
