apiVersion: v1
kind: Namespace
metadata:
  name: nullplatform-tools
  labels:
    name: nullplatform-tools
---
{{- if not (lookup "v1" "Namespace" "" .Values.namespaces.nullplatform) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.nullplatform }}
  labels:
    name: {{ .Values.namespaces.nullplatform }}
{{- end }}
