#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Skip commitizen if commit is automated/generated (like rebase, merge etc.)
if [ -z "${HUSKY_SKIP_HOOKS}" ] && [ -t 1 ]; then
  exec < /dev/tty && npx cz --hook || true
fi