name: publish-helm-charts
on:
  release:
    types:
      - published
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Download chart dependencies
        run: helm dependency update ./charts/base
      - name: Package Helm chart and output to releases directory
        run: helm package ./charts/base --destination ./releases
      - name: Generate Helm repository index in releases directory
        run: helm repo index ./releases --url https://nullplatform.github.io/helm-charts
      - name: Push changes to GitHub
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ./releases
          git commit -m "Publish new chart version"
          git push origin main
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './releases'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
